### ISSUE TITLE
Playing in the playground

### ISSUE THREAD

**Issue by MrMaint** [openscad/openscad-playground#34]
I noticed that color("red")cube([10,10,10],center=true); does not produce a red cube. I use OpenSCAD to teach programming to grade school age students and color is very important to their creations. Is this just a auto render problem, or is the color command not supported?

I also noticed that every time the rendering updates it resets the view angle. If after rendering you use the mouse to rotate the model, it will return to the not rotated position if you make an edit or press render.

Is "use <library.scad>" supported? Where would the "library.scad" file need to be stored? 
I ended up just copying the file into the editor.

**Comment by ochafik** [comment]
Hi @MrMaint ,

Thanks for giving the playground a try!

As it turns out, I'm working on color support for exports right now (see https://github.com/openscad/openscad/pull/5180), but it's not fully ready for prime time yet.

Sneak peak view in the playground: https://ochafik.com/openscad3 (as an added benefit it preserves the camera angle between renders, although not yet through a full tab refresh).

If you're able to install a desktop version (https://openscad.org/ - please do prefer a dev snapshot and enable experimental features like `manifold`), there are "best effort" builds w/ color export support (OFF format only - feature `render-color` in the settings), e.g [windows](https://app.circleci.com/pipelines/github/openscad/openscad/5104/workflows/5bb85a6d-3259-4aa0-a12a-97e2916cc34b/jobs/19712/artifacts) / [AppImage](https://app.circleci.com/pipelines/github/openscad/openscad/5104/workflows/5bb85a6d-3259-4aa0-a12a-97e2916cc34b/jobs/19714?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) binaries.

**Comment by ochafik** [comment]
> Is "use <library.scad>" supported? Where would the "library.scad" file need to be stored?
> I ended up just copying the file into the editor.

Not supported yet, except with the libaries bundled (eg BOSL2…)

it’s on my radar 👀

**Comment by ochafik** [comment]
Colors now work in the deployed web playground, and so does the customizer

https://ochafik.com/openscad2

<img width="557" alt="image" src="https://github.com/openscad/openscad-playground/assets/273860/97027a6d-2153-4d72-85d2-b06c32fafcf3">

**Comment by ochafik** [comment]
Closing this as color & relatively stable camera orientation are in, and additional file support is tracked in https://github.com/openscad/openscad-playground/issues/42

Thanks again!
