### ISSUE TITLE
Wrong colors on some shapes in the new colored STL viewer

### ISSUE THREAD

**Issue by pks5** [openscad/openscad-playground#75]
Hello,

first of all: thank you very much for the new colored STL viewer - it's so awesome. A game changer for my application!

However i found a bug with the coloring:

<img width="1008" alt="Screenshot 2024-12-23 at 20 58 49" src="https://github.com/user-attachments/assets/33adb78c-08f0-497b-968d-8aacea87d3cf" />

For some reason, one side is black.

Here is a [live link](https://machineblocks.com/examples/slanted#roof-tile-4x2) to the above example.

Kind regards

**Comment by ochafik** [comment]
Hey @pks5, thanks for the enthusiasm and the bug report!

The issue here is the lighting & material I've baked into the GLB [here](https://github.com/openscad/openscad-playground/blob/8f51167d5ace997db2365bf2b07756aa33d4355c/src/io/export_glb.ts#L76). Ideally I'd need to create an ambient map, but for now I'll just tweak some knobs (https://github.com/openscad/openscad-playground/pull/77).

Awesome to see your usage of the playground, machineblocks looks super exciting! I've been toying with the idea of making the playground easier to embed, feel free to chime in on https://github.com/openscad/openscad-playground/issues/78 with your requirements :-)

**Comment by pks5** [comment]
Thank you! I will try whether the tweaks will fix the issue.

**Comment by pks5** [comment]
I can confirm your latest changes fixed that issue!

<img width="1148" alt="Screenshot 2024-12-24 at 16 26 44" src="https://github.com/user-attachments/assets/3bf2a2cc-6584-4275-96b9-0615a71c68b2" />

Thanks

**Comment by pks5** [comment]
I just found a similar issue on another model.

[You can find it here](https://machineblocks.com/docs/scad-crash-course-101), scroll down to rotations and chose the second model from the menu on the left.

<img width="1221" alt="Screenshot 2024-12-24 at 17 42 30" src="https://github.com/user-attachments/assets/037171d0-ca1a-43b5-b756-da9f4c298918" />

**Comment by ochafik** [comment]
Urgh, yeah my "fix" was silly, even the following simple repro looks dreadful:

```
include <BOSL2/std.scad>;
prismoid([40,40], [0,0], h=20);
```

I probably need to drop the lights & play w/ public/skybox-lights.jpg instead

**Comment by ochafik** [comment]
Should be fixed by https://github.com/openscad/openscad-playground/pull/93/commits/658f06e2fcb9b0c8243f53cfd650b83a3d1bd8f2

Please let me know if you find any more lighting issues
